import Head from 'next/head'
import { Inter } from '@next/font/google'
import Inicio from 'components/Inicio'
import Nav from 'components/Nav'
import Conteudo from 'components/Conteudo'
import Local from 'components/Local'
import Footer from 'components/Footer'
import Sao from 'components/Sao'
import BotaoVolta from 'components/BotaoVolta'



const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div>
      <Head>
        <title>Antônio Dutra Shopping</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BotaoVolta/>
      <Nav />
      <Inicio />
      <Conteudo />
      <Local />
      <Sao/>
      <Footer />

    </div>
  )
}
